/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAMD51 has 14 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8
#define GPIO_PIN_FUNCTION_J 9
#define GPIO_PIN_FUNCTION_K 10
#define GPIO_PIN_FUNCTION_L 11
#define GPIO_PIN_FUNCTION_M 12
#define GPIO_PIN_FUNCTION_N 13

#define RANGE_SWITCH_POSITION_5 GPIO(GPIO_PORTA, 8)
#define RANGE_SWITCH_POSITION_4 GPIO(GPIO_PORTA, 9)
#define RANGE_SWITCH_POSITION_3 GPIO(GPIO_PORTA, 10)
#define RANGE_SWITCH_POSITION_2 GPIO(GPIO_PORTA, 11)
#define RANGE_SWITCH_POSITION_1 GPIO(GPIO_PORTA, 12)
#define STATUS_LED_RED GPIO(GPIO_PORTA, 13)
#define STATUS_LED_GREEN GPIO(GPIO_PORTA, 16)
#define STATUS_LED_BLUE GPIO(GPIO_PORTA, 17)
#define MODE_LED_RED GPIO(GPIO_PORTA, 18)
#define MODE_LED_GREEN GPIO(GPIO_PORTA, 19)
#define MODE_LED_BLUE GPIO(GPIO_PORTA, 20)
#define USB_STATUS_LED_RED GPIO(GPIO_PORTA, 21)
#define USB_STATUS_LED_GREEN GPIO(GPIO_PORTA, 22)
#define USB_STATUS_LED_BLUE GPIO(GPIO_PORTA, 23)
#define USB_M GPIO(GPIO_PORTA, 24)
#define USB_P GPIO(GPIO_PORTA, 25)
#define EXTERNAL_TRIGGER GPIO(GPIO_PORTB, 3)
#define CURRENT_MONITOR GPIO(GPIO_PORTB, 8)

#endif // ATMEL_START_PINS_H_INCLUDED
